### ISSUE TITLE
Few comments on reviewing the code

### ISSUE THREAD

**Issue by superfashi** [JeffersonQin/syncat#1]
### Dereferencing nil pointers causing panic

The code unnecessarily dereferences nil pointer in error handling, for example 
https://github.com/JeffersonQin/syncat/blob/c4765a6e250554bd8077abfdc5b777bd67e293a9/pkg/database/database.go#L72-L75 and https://github.com/JeffersonQin/syncat/blob/c4765a6e250554bd8077abfdc5b777bd67e293a9/pkg/database/database.go#L83-L86 (not a complete list).

When an error occurs, a `(nil, err)` pair is usually returned, therefore no need to close the handle additionally. (The behavior is similar to C syscalls). And if a `Close` is called on a nil pointer, it will result in panic.

### Unnecessary defer function arguments

For some reason I see usages like https://github.com/JeffersonQin/syncat/blob/c4765a6e250554bd8077abfdc5b777bd67e293a9/pkg/database/database.go#L115-L117. This is unnecessary since anonymous functions have access to the scope variables. So there is no need to pass the pointers in.

**Comment by JeffersonQin** [comment]
Thanks! I will fix them as soon as possible.
